---
title: "Design 4 - Osmoregulation and Excretion"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "How does your animal obtain enough water?"
date: 2023-11-27
format: 
  html: default 
  pdf: default
  docx: default
categories: [design project, design 4, osmoregulation, excretion, metabolism, protein, DMR, urine]
---

___Last one!___ _Feel free to use this to design a project on osmoregulation and excretion or follow your interests and design your own project, if you wish!_ If you want to design your own, please run it by me so I can advise on on whether you have enough.

# Suggestions

Set the initial conditions for the osmoregulation balance sheet. Was your animal terrestrial or aquatic?  What was the osmolarity of its body fluids?  If your animal was ureo-osmoconforming, designate the proportion of total osmolarity due to urea and the proportion due to other solutes.  If your animal was aquatic, what was the osmolarity of the medium?  If your animal was terrestrial, what were the temperature and relative humidity of the air?  Did your animal need to use evaporation for cooling?  How many kJ/day must have been lost through evaporation (from temperature design)?  How many grams of water must have been evaporated to lose this much heat (heat of evaporation = 2.4 kJ/g water).

Make up a _qualitative_ (no numbers yet) _water balance sheet_ for your animal.  List all of the ways that the animal gains and loses water (water in and water out), and explain them in words. 

Calculate theoretical values for the elements of the _water balance sheet_.  When calculating _urine volume_, calculate the volume required to excrete nitrogenous wastes, given the maximum possible nitrogen concentration. _Assume the animal is in water balance_ (set total water in = total water out).  Calculate the amount that the animal must drink to stay in water balance.  If this value is negative, then the animal has more water than it needs and will produce a more dilute urine.  Increase urine volume to compensate for this, and assume zero drinking.

Make up a _qualitative solute balance sheet_ for your animal (solutes in and solutes out).  List all of the ways that the animal gains and loses solutes, and explain them in words.

_Describe the excretory organs of your animal_.  What nitrogenous end product did your animal excrete (ammonia, urea, uric acid)?  What was the role of the _kidney_ in nitrogen excretion and water and solute balance?  How did it perform these functions?  Did the animal have other excretory organs (salt glands, chloride cells in gills, etc.)?

 
\[[pdf](4.Osmoregulation.pdf)\] version of this sheet  
\[[Helpful resources](design4-resources.qmd)\] - a few helpful papers. Withers 1992 is also very good on this topic.

Withers, P.C. 1992. _Comparative Animal Physiology_, Saunders College Publishing