---
title: "Submitting Design 3"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "How to be a good colleague and provide very helpful feedback"
date: 2023-11-17
format: 
  html: default 
  pdf: default
  docx: default
categories: [design project, design 3, respiration, ventilation, circulation, DMR, activity ]
---

# Turn in your Design 3 

1) Please be sure to __name the file using the naming convention FirstAuthorLastName_SecondAuthorLastName.pdf__ so that your peers can find the correct paper to review. Be sure to put the first author first.

For example: "_Fisher_Gao.pdf_"

2) Post your draft paper on the shared Google Drive by midnight Monday. \[[Upload here](https://drive.google.com/drive/folders/18lT2pGEZws_rrgD6IxfKCPyPGOFIX0IP?usp=share_link)\]

Note:  All Design papers are in the __Shared Google Drive > DesignProjects > ...__ 

<!----
3) Post your final draft by midnight on Wednesday 10/4 \[[Upload here](https://drive.google.com/drive/folders/1lRh1ZuG4q453Oo0xxSZWDgYWxuD6oo9e)\]
---->

## Complete your Peer Critique 

:::{.callout-note}
# Reference materials
- Find your \[[Review assignment](https://docs.google.com/spreadsheets/d/1LwboLhEIF_F5TcaXQGQMH2l3Y1ZG8u1RwClk6yM3n4g/edit?usp=sharing)\] 
- Download your assigned manuscript. \[[Design 3 google drive folder](https://drive.google.com/drive/folders/18lT2pGEZws_rrgD6IxfKCPyPGOFIX0IP?usp=share_link)\].
- \[[Design 3 assignment](design3.qmd)\] 
 

__Print out the manuscript so that you can write comments directly on the report.__
:::

### _Read through the \[[content guidelines](PeerCritiqueGuidelines.pdf)\]_. 
 
### _Read your assigned manuscript. Be a good colleague._ 
- Your main task is to __critique the content__ - please go through their __analysis__ and look for any improvements that could help. _Catch any errors, and they will be __extremely grateful__._ 
- __Identify any cool results to point out or other discussion points that may increase significance.__
- As you go, mark it with brief comments or corrections. _Please do not correct each instance of the same type of error. Just point it out the first time._ 
-  __Focus on improvements__ that would provide the __biggest payoff__. Be explict
it (of course, don't be mean – just state the facts). 
-  When you receive your critique, it really helps to have a thick skin – we are working together to help each other produce the best final draft possible. 

### _Prepare your ~2 page __written critique__ for the authors_. Please submit by Wednesday. 

  + __Begin your review with a positive statement__ before going into problems.  A critique is mostly negative – that's just the nature of the beast. As scientists, we are most interested in knowing exactly what is wrong, poorly stated, or unconvincing _so that we can correct it_. But it makes the medicine a little easier to swallow if you start with something nice.

  + Write __Major (overall) comments__ (about one paragraph). What was the best part of the manuscript? What were the major problems? The most significant shortcomings? Was it well-written and clearly organized?

  + Write __Specific comments__. For ideas on what to include for these sections, see Peer Critique guidelines:
    *  Content (specific comments on each section)
    *  Organization and Structure
    *  Style and Grammar
    *  Cited References

  + In general, pick the most significant comments to write up first. 
  
  + Any additional results or comparisions that would boost their intellectual signficance?

  + Any discussion points that they should add? 
  
  + _You are not obligated to provide more than two pages_ (i.e., don't correcting every little thing, just point out on the first instance, and let the authors learn from finding the rest). 

  + Evaluate __Effectiveness of Collaboration__. Did each partner contribute significantly and more or less equally? (can be as short as one sentence, but please elaborate if you need to).

  + Focus on __specific comments related to content__. However, if there are problems in other areas, please tell them clearly. 

### _Assign a numeric grade based on a 100% maximum scale._ 
It should be weighted (approximately) 60% Content, 20% Organization & Structure, 10% Style and Grammar, and 10% Cited References. 

__The grade you give will not affect their grade at all. But will help clarify for everyone how papers are evaluated.__ Help them get a better grade by being clear so that the final version can be as strong as possible. 

__Your peer-review grade (10 pts)__ will be based on the __quality of your critique__, including the reasonableness of the grade you assign.

### Submit by EMAIL to the two AUTHORS with cc to me
Give the __One marked up copy of the paper__ to the authors,

Thanks! Marguerite
