---
title: "Design 3 - option 2 - Circulation"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Blood and Circulatory system edition: How does your animalʻs circulation deliver enough oxygen to support its activities?"
date: 2023-11-06
format: 
  html: default 
  pdf: default
  docx: default
categories: [design project, design 3, oxygen, metabolism, DMR, circulation, blood, activity ]
---

# Suggestions for Circulation

_You have a choice in Design 3 projects. You may choose to model \[[Respiration](design3.qmd)\] instead of Circulation, if you like._

Again, you are free to take your design in any direction you wish.  Below are some suggestions:

1)  Draw a schematic diagram of the circulatory system of your animal.  Include the major target organs.  Does your animal have a single, partially divided, or fully divided circulation?  Discuss the functional implications of your animal’s system (and draw circulation during shunting, if this happens).

2)  Develop oxygen dissociation curves for your animal at rest.  Try to find examples from the textbook or from the literature of dissociation curves from an animal that is similar to your animal.  Then use a piece of graph paper to draw a non-Bohr shifted curve (representing the dissociation curve in the lungs).  Then select a reasonable pH change in the tissues during rest (-0.05 to -0.1 pH points) and a Bohr effect factor from Withers (1992, Table 15-4).  P$_{50}$ is the pO$_2$ for 50% oxygen saturation. Use these values to calculate P$_{50}$ and draw a Bohr-shifted oxygen dissociation curve for the tissues at rest.  What is the magnitude of the Bohr effect (the change in P$_{50}$ per unit change in pH, often expresses as $\Delta$log(P$_{50}$)/$\Delta$pH)?

3)  Develop an oxygen dissociation curve for your animal during exercise.  Increase the change in pH to a range that is more appropriate for the high CO2 levels present in the tissues during exercise (0.2-0.8 pH points, depending on intensity of activity).  Calculate p502 and draw a Bohr-shifted oxygen dissociation curve for the tissues during exercise (add this graph on the same diagram as the two graphs generated above).  

4)  Use your oxygen dissociation curves to calculate oxygen extraction from the blood at rest and during exercise.  Express this in mlO$_2$/ ml blood.

5)  Calculate resting heart rate for your animal from the allometric curves for heart rate.  

6)  From VO$_2$ at RMR, resting heart rate, and resting extraction, calculate the stroke volume of the heart at rest.  Calculate the cardiac output of your animal’s heart.  Estimate the volume of the whole heart.  How does this compare with a value calculated from the heart volume versus body mass values given in the notes?

7)  In order to deliver enough oxygen at MMR, different animals increase heart rate, stroke volume, and extraction by different amounts.  Given the value for extraction calculated in #4 above, how much must HR and/or SV increase to meet the increased VO2 at MMR?  What proportions of the increase in oxygen delivery are due to each of the components (SV, HR, extraction)?

Possible extras:  

- Design a hormonal and neural control system for the cardiac output.  
- Design resistance of peripheral vasculature – use variations in resistance to show how blood is distributed to different organs under different circumstances.  
- Make a quantitative design of heart shunts – shunting will affect C$_a$O$_2$ and C$_v$O$_2$.  

Be sure to check out the 

- \[[Design 3 Process](design3-process.qmd)\] for helpful tips 
- \[[Index of papers](design3-resources.qmd)\] for helpful resources. Check it out!

\[[pdf](3a.Circulation.pdf)\] version of this sheet

Withers, P.C. 1992. _Comparative Animal Physiology_, Saunders College Publishing