---
title: "4\\. Cardiac Function"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "The vertebrate heart and its regulation"
date: 2024-09-17
format: 
  html: default 
  pdf: default
categories: [module 4, week 4, cardiac function, cardiac cycle, cardiac regulation, MMR ]
---

This week we will learn more about cardiac morphology, function, and regulation. There are multiple very short (but important) readings, and some longer readings to skim. Donʻt worry about understanding every detail in the readings, but rather look over the discussion questions first and hunt through the readings for those topics, skimming over the rest. _These are going to be important topics for the next few labs._ 

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Tuesday we will finish heterothermy and start cardiac function. \[[Heart Discussion Questions and readings](../../discussions/Discussion-Week4-heart-function.pdf)\] 
2. Thursday we finish heart control and use part of the class to talk about the design projects. 
:::

### Announcements/Reminders

-  Please wear __comfortable shoes to lab__ for running up and down stairs. \[[Lab 4](../../labs/Lab4-human-ecg/Lab4.qmd)\]
-  HW1 solutions are posted on window of EDM101 lab.
-  HW2 due in class
-  If you are resubmitting your Background Bullet Points, due by Friday at midnight. Email pdf. 
-  Design 1 draft due on Monday 9/23 by 5pm  


### Week 4 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Hao | Abby |  Ilan |
|2| Christian | James  |   Sean   |  
|3| Ashton | Joshua | Tamako |
|4| Kylee |   Veronica | |
|5| Adam |   Mohamad | Vivian |

## Tuesday
   
- Finish up Heterothermy \[[questions 2-4](../../discussions/Discussion-Week3-temperature.pdf)\] \[[slide deck](../../powerpoints/3.Temperature.pdf)\] 
- Begin Cardiac Cycle \[[slide deck](../../powerpoints/4.CardiacCycle.pdf)\] \[[discussion](../../discussions/Discussion-Week4-heart-function.pdf)\]

## Thursday

- Cardiac Function/Regulation continued 
- Design 1 chat - come with your questions!


# For Next Week

1. Design 1 draft due on Monday 9/23 by 5pm. \[[assignment](../../projects/design1.qmd)\] \[[pdf](../../projects/1.MetabolismTempDesign1.pdf)\] \[[FAQs](../../projects/design1-FAQ.qmd)\] \[[turn in instructions](../../projects/design1-turnin.qmd)\]\[[post here](https://drive.google.com/drive/u/0/folders/1ZDvNTCNeE2OKg6W_fqvj6BQmo3GTcdOo)\]
2. Next Lab session: Design 1 peer critique session \[[see peer review instructions](../../projects/design1-turnin.qmd)\]
3. Please fill out the TEAMMATES evals, released on Thursday, due by MONDAY. (check your email)




