project:
  type: website
  output-dir: docs

website:
  title: "ZOOL430 Animal Physiology and Laboratory"
  site-url: https://mbutler808.github.io/animalphys-2025
  description: "Course website for Animal Physiology"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "General Information"
        menu:
        - text: "Syllabus"
          href: syllabus.qmd
        - text: "Schedule"
          href: schedule.qmd
      - text: "Course Materials"
        menu:
        - text: "Lectures"
          href: lectures.qmd
        - text: "Labs"
          href: labs.qmd
        - text: "Slides"
          href: slides.qmd
        - text: "Projects"
          href: projects.qmd
        - text: "Resources"
          href: resources.qmd
      - icon: github
        href: https://github.com/mbutler808
      - icon: twitter
        href: https://twitter.com/mbutler808
      - icon: rss
        href: index.xml
format:
  html:
    css: styles.css
    theme: simplex
    toc: true

editor: visual

execute:
  freeze: auto

