---
title: "Schedule"
description: |
 Schedule and course materials for Animal Physiology (Zool 430 Fall 2025).
tbl-colwidths: [9,3, 20, 20,30]
format: 
  html: default 
  pdf: default
  docx: default
---
```{r}
#| echo: false
```

## Assignment Schedule _SUBJECT TO CHANGE_


::: column-page
|   |   | Class Topic | Assignment Due  | Lab | 
|----|----|----|----|----|
|Week 1|||||
| 8/27 | W | Intro to Course/Megalodon Discussion \[[html](posts/2025-08-27-megalodon-model/index.qmd)\] \[[paper](https://www.nature.com/articles/s41586-023-06381-1)\] \[[Google Drive copy](https://drive.google.com/drive/folders/1M8ygipZEd9OUdld45C4BGgfJw2KWUKYk)\] | (Reading Assessment)  | Lab1: PC1-G-HR/Data analysis \[[overview](labs/Lab1-heart-rate-and-data-analysis/Lab1.qmd)\] \[[podcast](https://youtu.be/pujrG6zhTJE)\] \[[lab manual](labs/Lab1-heart-rate-and-data-analysis/Lab1-data-aquistion-finger-pulse.pdf)\] \[[protocol](labs/Protocols/p1-intro-finger-pulse.pdf)\] |   
|   | F | Library Day - Meet at Hamilton \[[html](posts/2025-08-29-library-day/index.qmd)\]|   |   |   
|Week 2|||||
| 9/3  | W | Metabolism \[[html](posts/2025-09-03-metabolism/index.qmd)\] \[[reading assignment and questions](discussions/Discussion_Week_2.pdf)\] \[[HWA readings](https://drive.google.com/drive/folders/1ONGdTPdeQz2lgGgAiWyZ_yGRmmcNSwoV)\] |   | Lab2: PC2-G-Honolulu Zoo \[[lab manual](labs/Lab2-zoo/Lab2.qmd)\] |   
| | F | Size and Scaling \[[podcast](https://youtu.be/_NDNa_3Bon8)\]|   |  |   
|   | F |  | Background Design 1 \[[html](projects/0.BackgroundBulletPoints.qmd)\] |   |   
|Week 3|||||
| 9/10 | W | Temperature \[[html](posts/2025-09-10-temperature)\] \[[discussion](discussions/Discussion_Week_3_temperature.pdf)\] |  PS1: Metabolism \[[pdf](homework/HW1metabolism.pdf)\] | Lab3:PC3-IWS-Peripheral Circ/Dive Resp \[[overview](labs/Lab3-human-peripheral-circulation-dive-response/Lab3.qmd)\]  |   
|   | F | Iterative Method/Heterothermy  |  |   |   
|Week 4|||||
| 9/17  | W |  Finish Temperature/Cardiac Function \[[html](posts/2025-09-17-cardiac-function/cardiac.qmd)\]  | PS2: Temperature \[[pdf](homework/HW2heat_temp.pdf)\]   |  Lab Practical / Lab4: PC3-G-ECG/Cardiac Function \[[overview](labs/Lab4-human-ecg/Lab4.qmd)\] | 
| | F | Design 1 chat |  |  | 
|   | F |  | |   |   
|Week 5|||||
| 9/22  | M |   | Design 1 Due \[[assignment](projects/design1.qmd)\] \[[pdf](projects/1.MetabolismTempDesign1.pdf)\] \[[FAQs](projects/design1-FAQ.qmd)\] \[[turn in](projects/design1-turnin.qmd)\]  | 
| 9/24  | W | Sustained Metabolic Scope Paper \[[discussion](discussions/Discussion-Week5-metabolic-ceiling.pdf)\] \[[Hammond and Diamond 1997](https://drive.google.com/drive/u/1/folders/1psPVIMIJVUuySxp9MHSQxxAhlvy-O9kK)\],  \[[optional: Peterson et al. 1990](https://drive.google.com/drive/u/1/folders/1psPVIMIJVUuySxp9MHSQxxAhlvy-O9kK)\] |  | Design Critique Session/Peer Critique 1 \[[turn in](projects/design1-turnin.qmd)\] |   
| | F | Design 1 Workday |  | |   
|Week 6|||||
| 10/1  | W | Feeding  \[[html](posts/2025-10-01-feeding/feeding.qmd)\] \[[discussion](discussions/Discussion-Week6-feeding-digestion.pdf)\] | | |  
| | F | Digestion  |   |  Lab5: PC1-IWS-Toad Heart \[[overview](labs/Lab5-toad-heart/Lab5.qmd)\]  |  
| | F |   | Design 1 Rewrite \[[Due midnight](https://drive.google.com/drive/folders/1lRh1ZuG4q453Oo0xxSZWDgYWxuD6oo9e?usp=sharing)\]   |   |     
|Week 7|||||
| 10/8 | W | Sample Problem \[[html](posts/2025-10-08-clauss-neurons/neurons.qmd)\] Max Size Herbivores Paper Claus 2003 \[[on drive](https://drive.google.com/drive/u/1/folders/1SceuF9tz_pD9J7lUrxbZbGAgIDIIhMJI)\] |  PS3: Feeding & Digestion \[[pdf](homework/HW3feeding_digestion.pdf)\]  |  Lab6: PC2-G-Lobster Heart \[[overview](labs/Lab6-lobster-heart/Lab6.qmd)\] |   
|   | F | Neurons \[[html](posts/2025-10-08-clauss-neurons/neurons.qmd)\] \[[discussion](discussions/Discussion-Week7-neurons-signal-propagation.pdf)\] |   |   |   
|Week 8|||||
| 10/15  | W | Synapses/Sensory Receptors  |  |  Design Presentations  | 
| | F | Muscles \[[html](posts/2025-10-22-muscles/muscles.qmd)\] \[[discussion](discussions/Discussion-Week8-muscle.pdf)\] |   |   |   
|Week 9|||||
| 10/22 | W | Motor Control \[[html](posts/2025-10-22-muscles/muscles.qmd)\] \[[discussion](discussions/Discussion-Week8-muscle.pdf)\]| Design 2 Feeding & Digestion \[[html](projects/design2-FAQ.qmd)\] \[[resources](projects/design2-resources.qmd)\] \[[turn in](projects/design2-turnin.qmd)\] | Lab 7:PC1-G-Vertebrate Action Potential \[[overview](labs/Lab7-toad-nerve/Lab7.qmd)\] |     
| | F | Biomechanics  | PS4: Neurons \[[pdf](homework/HW4neurons.pdf)\], Peer Critique 2 \[[see turn in](projects/design2-turnin.qmd)\] |    |   
| | F | | Design 2 Feeding & Digestion \[[html](projects/design2-FAQ.qmd)\] \[[resources](projects/design2-resources.qmd)\] \[[turn in](projects/design2-turnin.qmd)\] |  |     
|Week 10|||||
| | M |   |  Peer Critique 2 \[[see turn in](projects/design2-turnin.qmd)\] |    |   
| 10/29 | W | Finish Muscles/Biomechanics \[[html](posts/2025-10-29-biomechanics-locomotion/biomechanics-locomotion.qmd)\] \[[discussion](discussions/Discussion-Week9-biomechanics-locomotion.pdf)\] |  |  Lab8: PC2-G-Human Muscle \[[overview](labs/Lab8-human-emg/Lab8.qmd)\] |   
|   | F | Locomotion   |   |  |   
|   | F |  | Rewrite Design 2 \[[Due Friday midnight](https://drive.google.com/drive/u/0/folders/1PB_2tkTES9yZrxmBkgfMubEcw3f37JBP)\]  |  |   
|Week 11|||||
| 11/5 | W | Blood and Respiration \[[html](posts/2025-11-05-blood-respiration/blood-respiration.qmd)\] |  | Lab9: PC3-G-Toad Muscle \[[overview](labs/Lab9-10-toad-muscle/Lab9-10.qmd)\] |  
|   | F | Blood and Respiration |    |  |   
|   | F |  |  PS5: Muscles & Biomech \[[pdf](homework/HW5muscles-biomechanics.pdf)\]  |  |   
|Week 12|||||
| 11/12  | W | Aquatic Respiration \[[html](posts/2025-11-12-ventilation/ventilation.qmd)\] |   | Lab10:PC1-I-Toad Muscle Independent \[[overview](labs/Lab9-10-toad-muscle/Lab9-10.qmd)\] |   
|  | F | Aerial Respiration  | PS6: Respiration \[[due at start of class](homework/HW6respiration.pdf)\]   | |   
|Week 13|||||
| 11/19 | W | Finish Respiration/Begin Osmoregulation \[[html](posts/2025-11-19-osmoregulation/osmoregulation.qmd)\] |  | Lab 11: PC1-G-Human EEG \[[overview]\] |   
|   | F | Symmorphosis: [Weibel, Taylor, and Hoppeler (1991)](https://drive.google.com/file/d/1Td1DRJpE398Mj50m5r7bm4ooiinkchct/view?usp=share_link) The concept of symmorphosis: A testable hypothesis of structure-function relationship. PNAS 88:10357-61 |  |  |   
|   | F |   |  Design 3 Resipration, Peer Critique 3  \[[html](projects/design3-process.qmd)\] \[[resources](projects/design3-resources.qmd)\] \[[turn in](projects/design3-turnin.qmd)\] |   |   
|Week 14|||||
| 11/26 | W | Osmoregulation 2 \[[html](posts/2025-11-26-osmoregulation2/osmoregulation2.qmd)\] |  | No Labs  |   
|   | F | __Thanksgiving Holiday__  |  |  |   
|Week 15|||||
| 12/3 | W | Excretion \[[html](posts/2025-12-03-excretion/excretion.qmd)\] |   | Lab 12: PC2-G-Human Renal \[[overview](labs/Lab12-human-renal/Lab12.qmd)\] |   
|   | F | Excretion 2 | PS7: Osmoregulation \[[pdf](homework/HW7Osmoregulation.pdf)\] |  |   
|   | F |  | Design 3 Rewrite |   |   
|Week 16|||||
| 12/10  | W | Student Presentations |   | Turn in Lab 12 |   
|  | F | Student Presentations | Design 4: Osmoreg/Own (draft optional) \[[html](projects/design4.qmd)\] \[[resources](projects/design4-resources.qmd)\] |    |   
||||||
| 12/19 | F | Finals Week | Design 4 Due |   |   
||||||
:::





