---
title: "9\\. Biomechanics and Locomotion"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Now we get to the fun stuff!"
date: 2025-10-29
format: 
  html: default 
  pdf: default
categories: [module 9, week 10, biomaterials, biomechanics, locomotion, aquatic, terrestrial, aerial, muscles, skeletons ]
---

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Wednesday we will finish Muscle Discussion and move on to biomechanics and locomotion
2. Friday we will continue locomotion.
3. Lab this week is the \[[Vertebrate (Toad) Nerve Lab](labs/Lab7-toad-nerve/Lab7.qmd)\]! Pay attention to refining your prelab. 
:::

### Announcements/Reminders

-  In order to give you a little more time on the Design 2 Rewrite, I have swapped the HW5 Mucles/Biomechanics \[[HW5](../../homework/HW5muscles-biomechanics.pdf)\] to be due __Monday 11/3__ and 
-  So Design 2 Rewrite will be __due Friday 11/7__ by midnight into the "Final" folder. \[[turn in](../../projects/design2-turnin.qmd)\]  
-  Do discussion TEAMMATES eval, released each Friday, due by Wednesday.
-  Getting to the end, folks! 
-  __Halloween Extra Credit__ - come dressed up!

### Week 10 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Dallas | Niki | Emma|
|2| Alice | Carla | Manuel |
|3| Darwin | Trey | Peigi |
|4| Kyra | Reagan  | Paris |

## Wednesday
 
- Finish Muscle Discussion \[[discussion](../../discussions/Discussion-Week8-muscle.pdf)\] \[[slide deck 2](../../powerpoints/8a.MusclesII.pdf)\]

### Muscle Design podcast 

{{< video https://youtu.be/XPgHg2lmc5M >}}

- Begin Biomechanics and Locomotion \[[discussion](../../discussions/Discussion-Week9-biomechanics-locomotion.pdf)\] \[[slide deck 1](../../powerpoints/9a.Biomechanics.pdf)\]

## Friday 

- Biomechanics and Locomotion \[[discussion](../../discussions/Discussion-Week9-biomechanics-locomotion.pdf)\] \[[slide deck 1](../../powerpoints/9a.Biomechanics.pdf)\]
  - Support vs. Locomotion
  - Material properties and functional design
    - stress and strain  
    - posture
  - Muscle architecture
  - Lever arms and gear ratios

- Terrestrial Locomotion \[[discussion](../../discussions/Discussion-Week9-biomechanics-locomotion.pdf)\] \[[slide deck 2](../../powerpoints/9b.TerrestrialLocomotion.pdf)\]
  - Cursorial adaptations
  - Trends in posture
  - Limb cycles and gaits (kinematics)
  - Ground reaction forces and joint forces (biomechanics)
  - Conservation of energy in running, walking jumping 

{{< video https://youtu.be/YlyaASmy-1E >}}

# Coming up Next Week

- Homework 5 Muscles & Biomechanics due Monday 11/03 \[[schedule](../../schedule.qmd)\]

::: callout-note
## Reminders and materials

:::


