---
title: "11b\\. Excretion"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "We are all slightly salty bags of water in the environment"
date: 2025-12-03
format: 
  html: default 
  pdf: default
categories: [module 11, week 14,  osmoregulation, excretion]
---

# Pre-class materials 

::: callout-important
## Letʻs finish strong!

- Two more content discussions, then final student presentions. 
- Everyone is so excited to watch your final presentations. Please sign up for a \[[presentation time](https://docs.google.com/spreadsheets/d/18ARk8XCpNsx-e65vF0LdGcSv0iXD3kNvOsOiQCFdar4/edit?usp=sharing)\] 
- __Attendance is mandatory__ at all remaining classes. 
- __Come prepared__ by __reading the book__, and our discussions can __probe deeper.__ This will make your __homeworks__, __labs__, and __papers__ so much easier. 
- __Remember that effort counts__, and will be taken into account in the final grades. If your grade is on the borderline, effort will translates into a "bump up".  You show effort in many ways, including attendance and sincere participation. 
:::


### Announcements/Reminders

-  Osmoregulation homework due Thursday at start of class. Last one! \[[schedule](../schedule.qmd)\]. 
-  \[[Design 3 final](https://drive.google.com/drive/u/0/folders/12I8sX5sAmbiAejZk8hbQELVuQiFA1y0S)\] due Friday by midnight. 
-  Please do TEAMMATES after Thursday. 
-  Last lab this week! __Prepare for the Human Renal Lab starting from the night before lab.__ \[[lab 12](../../labs/Lab12-human-renal/Lab12.qmd)\]
-  Design 4 is posted \[[suggestions](../../projects/design4.qmd)\] or feel free to pursue your own interests and design your own project!  Due the week of finals. 

### Week 14/15 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Abby|  Adam|  Vivian|
|2| Ilan|    Veronica|  Ashton|  
|3| James| Christian|   Sean|    
|4| Hao|    Kylee|  Mohamad|

## Tuesday 
- Welcome back from Thanksgiving! 
- \[[Excretion questions](../../discussions/Discussion-Week11b-excretion.pdf)\] \[[slide deck 1](../../powerpoints/11.Osmoregulation.pdf)\] \[[slide deck 2](../../powerpoints/11b.Osmoregulation_SaltWater.pdf)\] 
- Reading assignment: Withers skim pp. 841-845 (pick up the four main steps of Tubular Excretion),read 855- 874 (Vertebrate Kidneys) and pp. 874-886 (Nitrogen Metabolism)  or HWA pp.754-776, 782-785.

- Nitrogenous waste comes from protein metabolism. Think about nitrogenous waste (osmoreg question 5) and what mechanisms organisms have for their excretion (excretion questions 1,2)

| Group | | |  | | |
| ----  | ----  |----  |----  |----  |----  |
| Fish | Kidneys | Gills | Bladder | Intestines | |
| Amphibians | Kidneys | Gills | Bladder | Intestines | Skin | 
| Reptiles | Kidneys | | | Intestines | (Salt Glands)| 
| Birds | Kidneys | | | Intestines | (Salt Glands) |
| Mammals | Kidneys |  |  | |  |

: Organs involved in osmoregulation {#tbl-osmoorg}


Osmoregulation Podcast
{{< video https://youtu.be/1vQxLFoPCmM >}}

## Thursday
- Bird and Reptile Excretion! We will have a fascinating discussion on reptile and bird excretion \[[notes](../../powerpoints/11c.Avian_Reptilian_Osmoregulation_Notes.pdf)\]

## Next Week
- Begin Final Presentations




