---
title: "5\\. Feeding"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Food! Glorious food!"
date: 2025-09-24
format: 
  html: default 
  pdf: default
categories: [module 5, week 5, food, feeding, nutrient composition, DMR]
---

Fridayʻs discussion will be on a Sustained metabolic scope paper that has some data and interesting tidbits relevant for your Design 1. Next we will continue talking about feeding (our favorite topic!) and digestion.   

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Friday \[[Metabolic Ceilings](../../discussions/Discussion-Week5-metabolic-ceiling.pdf)\] 
:::

### Announcements/Reminders

-  This week during our lab sessions we will have our design 1 critique sessions. Please check which paper you have been assigned to review, and bring your completed review with you to lab. See instructions here \[[Design 1 turn in](../../projects/design1-turnin.qmd)\]. 
- Post your final draft by midnight on Friday 10/3 \[[Upload here](https://drive.google.com/drive/folders/17jxQxSR74Q_qeiy3JkIO8B5CgkUdHwFz?usp=sharing)\].  
-  Do discussion TEAMMATES eval, released each Friday, due by Wednesday.

### Week 5 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Darwin |  Xavier |  Emma |
|2| Alice  |  Trey   |  Reagan |
|3| Dallas |  Peigi  |  Paris |
|4| Kyra   |  Niki   |    |
|5| Carla  |  Manuel |    |


## Snakes Drink Weird!

{{< video https://youtu.be/_r3gG6NjNKQ >}}

## Wednesday
   
- Feeding lecture

## Friday

- Paper Discussion \[[Metabolic Celings](../../discussions/Discussion-Week4-metabolic-ceiling.pdf)\]

# For Next Time

::: callout-note
## Reminders and materials
- Make an appointment for you and your partner to get help from me on your design projects. Both must attend. <https://calendly.com/mbutler808/office-hours>
- Next week we will start Feeding & Digestion \[[discussion](../../discussions/Discussion-Week5-feeding-digestion.pdf)\]

:::


