---
title: "10\\. Blood and Respiratory Media"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Now we get to move it move it!"
date: 2025-11-05
format: 
  html: default 
  pdf: default
categories: [module 10, week 11, blood, respiratory media, aquatic, terrestrial, aerial ]
---

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. __No Class on Tuesday -- Election Day!__ - But to stay on track please be sure to watch the podcast and review \[[locomotion](../2024-10-29-biomechanics-locomotion/biomechanics-locomotion.qmd)\]  
2. Thursday we will move on to blood and respiratory media 
3. Lab this week is on \[[toad muscle](../../labs/Lab9-10-toad-muscle/Lab9-10.qmd)\]! Pay attention to refining your prelab. 
4. Think hard about a __hypothesis for your independent toad muscle__ lab next week. 
:::

### Announcements/Reminders

-  Due Friday Homework 5 via Laulima \[[schedule](../../schedule.qmd)\]. You should be able to complete all of the questions except the last one. Because of the holiday, we will talk about that a bit on Thursday. 
-  Do discussion TEAMMATES eval, released each Thursday, due by Monday.
-  Getting to the end, folks! 

### Week 11 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1|James |Abby|Ilan|
|2|Christian|Kylee| Veronica|
|3|Ashton|Mohamad|Vivian|
|4|Hao| Adam|Sean | 


## Tuesday is Election day

__No Class__ - Please watch the podcast and review on your own. Iʻll talk briefly on this on Thursday. 

- Terrestrial Locomotion \[[discussion](../../discussions/Discussion-Week9-biomechanics-locomotion.pdf)\] \[[slide deck 2](../../powerpoints/9b.TerrestrialLocomotion.pdf)\]
  - Cursorial adaptations
  - Trends in posture
  - Limb cycles and gaits (kinematics)
  - Ground reaction forces and joint forces (biomechanics)
  - Conservation of energy in running, walking jumping 

{{< video https://youtu.be/YlyaASmy-1E >}}
 

## Thursday 


- Blood and Respiratory Media \[[discussion](../../discussions/Discussion-Week10-blood-ventilation.pdf)\] \[[slide deck](../../powerpoints/10a.Blood.pdf)\] \[[slide deck2](../../powerpoints/10b.Ventilation.pdf)\]
  - Hemoglobin and O2 delivery
  - Bohr effect
  - Air vs. Water as respiratory media
  - Diffusion vs. Bulk Flow

{{< video https://youtu.be/t0Vf-RJleCE >}}

# Coming up Next Week

- Homework 6 Respiration Thursday 11/12 \[[schedule](../../schedule.qmd)\]

::: callout-note
## Reminders and materials

:::


