---
title: "11\\. Respiration-Osmoreguation"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Finishing off respiration and starting osmoregulation"
date: 2025-11-18
format: 
  html: default 
  pdf: default
categories: [module 11, week 13, ventilation, respiration, osmoregulation]
---

# Pre-class materials 


::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Tuesday we will finish respiration and Thursday begin osmoregulation. 
2. The Symmorphosis paper is a very interesting and important paper. It will be useful for design3 respiration. 
3. In Lab this week you will measure your own brain waves using EEG. Have fun! \[[manual](../../labs/Lab11-human-eeg/Lab11.qmd)\]! 
:::

### Announcements/Reminders

-  Due Thursday at the start of class-- Homework 5 Q1,2,5 \[[schedule](../../schedule.qmd)\] 
-  Due Monday 11/25 at midnight - Design 3 draft
-  Please do your peer review for design 3 by Wednesday and send to colleagues and myself
-  Do discussion TEAMMATES eval, released each Friday, due by Monday.

### Week 13 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Abby|  Ashton| Adam|    
|2| Hao|   Kylee| Vivian|
|3| Ilan|    Mohamad| Veronica|
|4| James| Sean|  Christian| 


# Tuesday - 

## Aquatic Respiration, Fish Gills

- __Reading assignment:__ Withers Aquatic respiration: skim 565-72, read 573-4, 585-99, supplement
12-2. ALTERNATIVELY, read HWA chapter 22 + HWA 586-587 (countercurr) + HWA 590-594 (fish).
- \[[discussion pg 3, Q4-5](../../discussions/Discussion-Week10-blood-ventilation.pdf)\] \[[slide deck](../../powerpoints/10a.Blood.pdf)\] \[[slide deck2](../../powerpoints/10b.Ventilation.pdf)\]
- __Topics:__
  - Partial pressures of gasses and pO2 at sea level - the starting point. 
    + Influences of relative humidity
    + Altitude (total pressure) 
    + Henryʻs Law - dissolved O2 in water
  - Flow patterns: Countercurrent vs. Concurrent
  - Fish Gills 
    + Ventilatory pumps in fish (breathing patterns) 
  - Root Effect

Respiratory Pumps
{{< video https://youtu.be/2GPfu8ebZac >}}

## Finish aerial respiration questions 2, 3, 4 
- __Reading assignment:__ Withers pp. 609-631 OR HWA chapter 23 + Withers 626-632, skip invertebrates
- \[[discussion pg 4:2,3,5](../../discussions/Discussion-Week10-blood-ventilation.pdf)\] \[[slide deck2](../../powerpoints/10b.Ventilation.pdf)\]
- __Aerial Respiration Topics:__
  - Air flow patterns of vertebrates


Respiration the Movie 
{{< video https://youtu.be/clyu9h810n4 >}}

# Thursday - Symmorphosis
- __Reading assignment:__ Symmorphosis: Weibel, Taylor, and Hoppeler (1991) The concept of symmorphosis: A testable hypothesis of structure-function relationship. PNAS 88:10357-61 [Respiration Papers folder](https://drive.google.com/file/d/1Td1DRJpE398Mj50m5r7bm4ooiinkchct/view?usp=share_link)
- In class discussion

## Begin Osmoregulation
- __Reading assignment:__ Withers skim beginning Ch. 16 for definitions in list below, also read Water & Ion Budgets pp. 788-790, Vertebrates pp. 798-803, Terrestrial Environments pp. 806-812, Terr. Verts. 822-827.  Withers is actually very readable on this topic, and some of it will be familiar to you already:).
- \[[discussion](../../discussions/Discussion-Week11-osmoregulation.pdf)\] \[[slide deck](../../powerpoints/11.Osmoregulation.pdf)\] \[[slide deck 2](../../powerpoints/11b.Osmoregulation_SaltWater.pdf)\]
- definitions: 
    -   solutes, 
    -   osmosis, 
    -   osmolarity/osmolality, 
    -   ionoregulation, 
    -   osmoregulation/osmoconforming, 
    -   compatible solutes, 
    -   perturbing solutes, 
    -   counteracting solutes, 
    -   osmotic permeability (&formulae)
- The components of __Water Budgets__ (input/output) as well as __Ion Budgets__
- The water and ion challenges of __freshwater__, __marine__, and __terrestrial__ environments


Osmoregulation Podcast
{{< video https://youtu.be/1vQxLFoPCmM >}}



::: callout-note
## Coming up Next Week
- We will have class on Tuesday.
- No class on Thursday, no labs.  
- Submit your group labs to your TA by email at the regular time. 
- Happy Thanksgiving!
:::


