---
title: "6\\. Feeding"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Food! Glorious food!"
date: 2025-10-01
format: 
  html: default 
  pdf: default
categories: [module 5, week 6, food, feeding, nutrient composition, DMR]
---

Tuesday we will start talking about feeding (our favorite topic!) and Thursday we start digestion.   

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

2. Tuesday we will start Feeding & Digestion \[[discussion](../../discussions/Discussion-Week6-feeding-digestion.pdf)\]
:::

### Announcements/Reminders

-  This week we will have our first toad lab! Please wear shoes and bring your dissection kit (if you have one, if not we will provide).
-  Do discussion TEAMMATES eval, released each Thursday, due by Monday.

### Week 6 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Kylee |  Adam | Abby |
|2| Ashton  |  James |   Vivian |
|3| Christian  | Veronica |  Hao |
|4| Ilan |  Mohamad |  Sean |


## Snakes Drink Weird!

{{< video https://youtu.be/_r3gG6NjNKQ >}}

## Tuesday
   
- Feeding \[[slide deck](../../powerpoints/5.Feeding.pdf)\]


## Thursday

- Digestion \[[slide deck](../../powerpoints/5b.DigestiveSystems.pdf)\]

# For Next Time

::: callout-note
## Reminders and materials
- HW3 is posted \[[pdf](../../homework/HW3feeding_digestion.pdf)\] due Tuesday October 8. 
- Make an appointment for you and your partner to get help from me on your design projects. Both must attend. <https://calendly.com/mbutler808/office-hours>

:::


