---
title: "3\\. Temperature"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Heat and its implications for physiology"
date: 2025-09-10
format: 
  html: default 
  pdf: default
categories: [module 3, week 3, BMR, SMR, RMR, AMR, DMR ]
---

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Withers chapter 5. Look over the homework, handout, and discussion questions and skim the chapter, reading anything that you need to know. 
2. \[[Discussion Questions](../../discussions/Discussion-Week3-temperature.pdf)\] 
3. \[[Slide Deck](../../powerpoints/3.Temperature.pdf)\] - for your reference as we go through the material
:::

### Announcements/Reminders

-  Labs this week - Meet at Honolulu Zoo at 1:30pm. LMK if you need a ride from campus. \[[Read Lab 2](../../labs/Lab2-zoo/Lab2.qmd)\]. Bring:
  - Your lab notebook
  - A timing device (e.g. your phone)
  - Sun screen, hat, and sunglasses. It will be hot and sunny! 
  - Water
  - One hardcopy of Lab report to turn in
-  Next week we will do the \[[Toad Heart Lab](../../labs/Lab5-toad-heart/Lab5.qmd)\].
-  We will finish Metabolism and begin Temperature. 
-  HW1 due Tuesday in class, hand-written (you may submit as a group - week 2 if you wish). 
-  HW2 due next Tuesday in class (individual). 

### Week 3 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
| 1 |  Kyra | Dallas  |  Trey|
| 2 | Niki  | Carla  |  Xavier |
| 3 |  Peigi |  Alice | Manuel |
| 4 | Reagan  | Emma  |  |
| 5 | Paris |  Darwin |  |



:::{.callout-tip}
# Thought for the day

> Physiology is the story of evolution’s struggle to maintain an appropriate SA/D ratio in relation to the volume of an animal -- _Haldane_ 
:::
   
# 3. Temperature

## Modes of Heat Transfer

- __Conduction__
- __Convection__
- __Evaporative__
- __Radiative__

Animals also generate heat through __Metabolism__.

{{< video https://youtu.be/BHchDrboqEo >}}



Flux = C * $\nabla$ (Mass or Energy) 

Q = C * M $\nabla$ T

Where:
- Flux is the transfer of mass or energy
- $\nabla$ is the gradient symbol
- Q is heat
- C is a material property (resistance or insulation value)
- T is temperature

## Heat Balance 

Metbolic heat production is balanced by all mechanisms for heat exchange: 

$\Delta$H$_s$ = H$_m$ $\pm$ H$_c$ $\pm$ H$_r$ $\pm$ H$_e$

Where:  
$\Delta$H$_s$ = heat of storage  
H$_m$ = heat of metabolism  
H$_c$ = heat of conduction and convection  
H$_r$ = heat of radiation  
H$_e$ = heat of evaporation  

If an animal is in heat balance, Tb (body temperature) is stable. 

If $\Delta$H$_s$ is positive,  (Gains > Losses), then  Tb increases.  

If $\Delta$H$_s$ is negative,  (Gains < Losses), then  Tb decreases.  


## Body Temperature


## Q10 

{{< video https://youtu.be/T5O9UvSZ_-g >}}

## Iterative Method

{{< video https://youtu.be/pEzcZCTYPyE >}}


# For Next Time

1. \[[HW2](../../homework/HW2heat_temp.pdf)\] due on Tuesday in class. (Individual)
2. Finish temperature, begin \[[Cardiac Function](../../discussions/Discussion-Week4-heart-function.pdf)\]
3. Start working on design 1 calculations with your partner. See me for help \[[Office hours](https://calendly.com/mbutler808/office-hours)\]
4. Next Lab: \[[Toad Heart Lab](../../labs/Lab5-toad-heart/Lab5.qmd)\]
5. Please fill out the TEAMMATES for both discussion week 3 and Lab 2 group lab by WEDNESDAY. (check your email)


