---
title: "7\\. Herbivore Discussion and Neurons"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "You all know about action potentials, but how do they actually work? The details, and how they scale up in the biological heirarchy are so much more interesting."
date: 2025-10-08
format: 
  html: default 
  pdf: default
categories: [module 6, week 7, neurons, action potentials, electricity, signals ]
---

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. We will finish discussing Herbivores - Special Digestive Systems \[[slide deck](../../powerpoints/5b.DigestiveSystems.pdf)\] and a very interesting paper \[[Claus et al 2003](https://drive.google.com/drive/u/1/folders/1SceuF9tz_pD9J7lUrxbZbGAgIDIIhMJI)\] 
2. Friday start Neurons Discussion \[[discussion & reading assignment](../../discussions/Discussion-Week7-neurons-signal-propagation.pdf)\]
3. Please watch the podcasts below for Friday. 
4. We will probably continue Neurons next week.
:::

### Announcements/Reminders

- HW3 \[[pdf](../../homework/HW3feeding_digestion.pdf)\] due Friday.  
- This week will be our first invertebrate lab on the Lobster Heart. Please wear shoes and bring your dissection kit (if you have one, if not we will provide). \[[overview](../../labs/Lab6-lobster-heart/Lab6.qmd)\]
-  Do discussion TEAMMATES eval, released each Friday, due by Monday.

### Week 7 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Manuel | Xavier  |  |
|2| Alice |  Paris |   |
|3| Dallas |  Kyra |  Reagan |
|4| Niki  |  Emma |  Peigi  |
|5| Darwin  | Carla | Trey  |

## Wednesday
 
- Herbivores - Specialized Digestive Systems  \[[discussion](../../discussions/Discussion-Week6-feeding-digestion.pdf)\] \[[digestion slide deck](../../powerpoints/5b.DigestiveSystems.pdf)\]

- Max size herbivores \[[Claus et al 2003 paper](https://drive.google.com/drive/u/1/folders/1SceuF9tz_pD9J7lUrxbZbGAgIDIIhMJI)\]\[[Discussion](../../discussions/Discussion-Week7a-sampleproblem-ClaussEtAl.pdf)\] 

## Friday


- Start Neurons Discussion \[[discussion](../../discussions/Discussion-Week7-neurons-signal-propagation.pdf)\] \[[slide deck](../../powerpoints/6a.NeuronsRecording.pdf)\]

### Neurons podcast

{{< video https://youtu.be/GKPWD-Mer6s >}}
 

### Signal propagation podcast 

{{< video https://youtu.be/8Z8vW6FAJxY >}}



# For Next Time

- Signal Propagation \[[slide deck2](../../powerpoints/6b.Synapses.pdf)\]



::: callout-note
## Reminders and materials

:::


