---
title: "9\\. Muscles"
author:
  - name: Marguerite Butler  
    url: https://butlerlab.org
    affiliation: School of Life Sciences, University of Hawaii
    affiliation_url: https://manoa.hawaii.edu/lifesciences/
description: "Muscles are so cool! They are responsible for the incredible diversity of animal movemements"
date: 2025-10-24
format: 
  html: default 
  pdf: default
categories: [module 8, week 9, muscles, excitable tissues, contraction force, force, velocity, tension, sarcomere, muscle architecture ]
---

# Pre-class materials 

::: callout-note
## Read ahead

**Before class, you can prepare by reading the following materials:**

1. Muscle Discussion \[[discussion & reading assignment](../../discussions/Discussion-Week8-muscle.pdf)\] 
:::

### Announcements/Reminders

- \[[HW 4](../../homework/HW4neurons.pdf)\] due Friday 10/24 at start of class
-  Do discussion TEAMMATES eval, released each Friday, due by Monday.
-  Design 2 draft due by Monday at midnight see resources, FAQs on \[[Schedule](../../schedule.qmd)\] or under Projects Tab. 
    + I strongly recommend you submitting your calculations to me by Friday (10/24) or ASAP so that I can review your work before you complete the draft. Just put it in the Draft folder, labelled, and shoot me a DM on Discord letting me know itʻs there. 
    + CALCULATIONS: Write out what you are doing in a few words, the equations with all parameters defined and cited on the right hand side of the page, and show your work. 
    + Herbivore diets - please show it in two parts: (1) the VALUES you obtained from sources, including the %DM, (2) the final Nutrient % of fresh food used in your model after adding back water, etc.  
-  Peer critique of Design 2 due Wednesday next week by email to 2 authors and myself.    

### Week 9 Discussion Groups

| Group | Partner 1 | Partner 2 | Partner 3 |
|----|----|----|----|----|
|1| Carla | Peigi| Kyra |
|2| Paris | Niki| Reagan |
|3| Dallas|Manuel| Emma |
|4| Trey| Alice | Darwin| 

## Wednesday
 
- Start Muscle Discussion \[[discussion](../../discussions/Discussion-Week8-muscle.pdf)\] \[[slide deck](../../powerpoints/8.MusclesI.pdf)\]

### Muscles EMG podcast

{{< video https://youtu.be/6Z39ZqgixfY >}}


## Friday

- Continue Muscle Discussion \[[discussion](../../discussions/Discussion-Week8-muscle.pdf)\] \[[slide deck 2](../../powerpoints/8a.MusclesII.pdf)\]

### Muscle Design podcast 

{{< video https://youtu.be/XPgHg2lmc5M >}}


# For Next Time


::: callout-note
## Reminders and materials

- Next week Toad Nerve lab! Lab 7:PC1-G-Vertebrate Action Potential \[[overview](../../labs/Lab7-toad-nerve/Lab7.qmd)\]
:::


